name: glassmorphism
description: A Flutter package for implimentation of Glassmorphic UI easily.
version: 1.0.3
homepage: "https://www.instagram.com/theflutterfoundry"
repository: "https://github.com/RitickSaha/glassmorphism"
issue_tracker: "https://github.com/RitickSaha/glassmorphism/issues"

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter