name: glassmorphism
description: A Flutter package for implimentation of Glassmorphic UI easily.
version: 3.2.1
homepage: "https://github.com/AstrisDev/glassmorphism"
repository: "https://github.com/AstrisDev/glassmorphism"
issue_tracker: "https://github.com/AstrisDev/glassmorphism/issues"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
